function FileData_Pairs(x)
{
x.t("decrease","risk");
x.t("institute","(nci)");
x.t("intends","identify");
x.t("variations","either");
x.t("genome-wide","association");
x.t("providing","feedback");
x.t("identify","common");
x.t("increase","decrease");
x.t("gene","variations");
x.t("association","studies");
x.t("studies","initiative");
x.t("common","inherited");
x.t("logging","cagwas");
x.t("inherited","gene");
x.t("cancer","institute");
x.t("cancer","genome-wide");
x.t("national","cancer");
x.t("portal","following");
x.t("(nci)","intends");
x.t("initiative","national");
x.t("online","help");
x.t("help","providing");
x.t("cagwas","cancer");
x.t("cagwas","online");
x.t("cagwas","cagwas");
x.t("cagwas","data");
x.t("cagwas","using");
x.t("information","cagwas");
x.t("data","portal");
x.t("risk","cancers");
x.t("topics","logging");
x.t("either","increase");
x.t("following","topics");
x.t("using","cagwas");
x.t("cancers","information");
}
